services:
  llm-answer-engine:
    build: .
    env_file:
      - .env.docker
# uncomment the following to change the default config (ollama, etc)
#    volumes:
#      - $PWD/app/config.tsx:/home/node/app/app/config.tsx:ro
    ports:
      - 3000:3000
