version: "3"
services:
  llm-answer-engine:
    build: .
    environment:
      - OPENAI_API_KEY=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
      - GROQ_API_KEY=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
      - BRAVE_SEARCH_API_KEY=BSATW622E1QYoxvT7F6XhXC5GoUXaUC
      - SERPER_API=5b904ef9a655b6a85b36d24353c4896ab90634f7
# uncomment the following to change the default config (ollama, etc)
#    volumes:
#      - $PWD/app/config.tsx:/home/node/app/app/config.tsx:ro
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
